[package]
name = "gemini"
version = "0.1.0"
authors = ["Honza Pokorny <me@honza.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.4"
url = "2.1.1"
