[package]
name = "gemini"
version = "0.1.0"
authors = ["Honza Pokorny <me@honza.ca>"]
edition = "2018"

[dependencies]
url = "2.1.1"
structopt = { version = "0.3", default-features = false }
openssl = "0.10.31"
